### PR TITLE
Feature pom parsing

### LINKED ISSUE #8: Add pom.xml support
To gain all transitive dependencies

### PR DESCRIPTION
**Pull request by matthewkmayer**
I believe this fixes #8 .

### CODE REVIEW

**Comment by kitplummer** [comment]
This only grabs the 'first-degree' hard-defined dependencies right?  And not the transitive associations?

**Comment by matthewkmayer** [comment]
I'll take a look at that.  From the 10 defined deps the output file has 35 or so dependencies listed.  I'll give the tree view a quick gander to verify it's grabbing the transitive ones or not.

**Comment by matthewkmayer** [comment]
Here's an example of one with transitive deps.  We'll look at `org.eclipse.jetty:jetty-util:jar` at the bottom of the tree:

```
+- org.eclipse.jetty:jetty-server:jar:7.2.0.v20101020:compile
|  +- javax.servlet:servlet-api:jar:2.5:compile
|  +- org.eclipse.jetty:jetty-continuation:jar:7.2.0.v20101020:compile
|  \- org.eclipse.jetty:jetty-http:jar:7.2.0.v20101020:compile
|     \- org.eclipse.jetty:jetty-io:jar:7.2.0.v20101020:compile
|        \- org.eclipse.jetty:jetty-util:jar:7.2.0.v20101020:compile
```

It's present in the list version of dependencies:

`org.eclipse.jetty:jetty-util:jar:7.2.0.v20101020:compile`

I think that shows we get transitive deps unless I'm missing something.

**Comment by matthewkmayer** [comment]
Per Slackchat this needs to be formatted in the same way as the other project types as well as keep parent:child relationships with dependencies.

**Pull request closed without merging**
